# Generated by Django 4.1.6 on 2023-05-06 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0006_alter_mensaje_emisor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
