# Generated by Django 4.1.6 on 2023-05-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0008_mensaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='emisor',
            field=models.CharField(max_length=50),
        ),
    ]
