# Generated by Django 4.1.6 on 2023-05-06 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppClientes', '0013_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('autor', models.CharField(max_length=50)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotosblog')),
            ],
        ),
    ]
