# Generated by Django 4.1.6 on 2023-05-06 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMain', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelBlog',
        ),
    ]
